# Generated by Django 5.2.2 on 2025-06-11 20:30

import cbo.models.managers.user
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('max_occupations', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'plan',
            },
        ),
        migrations.CreateModel(
            name='PlanBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'plan_benefit',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('first_name', models.CharField(max_length=150, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=150, verbose_name='Sobrenome')),
                ('CPF', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='endereço de email')),
                ('telephone', models.CharField(max_length=15, verbose_name='Celular')),
                ('date_of_birth', models.DateField(verbose_name='Data de Nascimento')),
                ('occupational_registration', models.CharField(blank=True, max_length=15, null=True, verbose_name='Registro Ocupacional')),
                ('email_verified', models.BooleanField(default=False)),
                ('email_verification_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='cbo.plan')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'user',
            },
            managers=[
                ('objects', cbo.models.managers.user.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Cid',
            fields=[
                ('cid_code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('grievance_type', models.CharField(max_length=1)),
                ('sex_type', models.CharField(max_length=1)),
                ('stadium_stype', models.CharField(max_length=1)),
                ('irradiated_fields_value', models.IntegerField()),
            ],
            options={
                'db_table': 'cid',
                'indexes': [models.Index(fields=['cid_code', 'name'], name='cid_cid_cod_86c868_idx')],
            },
        ),
        migrations.CreateModel(
            name='FavoriteProceduresFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'favorite_procedures_folder',
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('occupation_code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, null=True)),
            ],
            options={
                'db_table': 'occupation',
                'indexes': [models.Index(fields=['occupation_code', 'name'], name='occupation_occupat_487537_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlanHasPlanBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=False)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbo.plan')),
                ('plan_benift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_point', to='cbo.planbenefit')),
            ],
            options={
                'db_table': 'plan_has_plan_benefit',
            },
        ),
        migrations.AddField(
            model_name='plan',
            name='points',
            field=models.ManyToManyField(related_name='plans', through='cbo.PlanHasPlanBenefit', to='cbo.planbenefit'),
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('procedure_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, null=True)),
                ('complexity_type', models.CharField(max_length=1, null=True)),
                ('sex_type', models.CharField(max_length=1, null=True)),
                ('maximum_execution_amount', models.IntegerField(null=True)),
                ('stay_day_number', models.CharField(max_length=4, null=True)),
                ('points_number', models.IntegerField(null=True)),
                ('minimum_age_value', models.IntegerField(null=True)),
                ('maximum_age_value', models.IntegerField(null=True)),
                ('SH_value', models.IntegerField(null=True)),
                ('SA_value', models.IntegerField(null=True)),
                ('SP_value', models.IntegerField(null=True)),
                ('stay_time_number', models.IntegerField(null=True)),
                ('competence_date', models.CharField(max_length=6, null=True)),
            ],
            options={
                'db_table': 'procedure',
                'indexes': [models.Index(fields=['procedure_code', 'name'], name='procedure_procedu_0d6d11_idx')],
            },
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('competence_date', models.CharField(max_length=6, null=True)),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbo.procedure')),
            ],
            options={
                'verbose_name': 'Description',
                'verbose_name_plural': 'Descriptions',
                'db_table': 'description',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('record_code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('competence_date', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'record',
                'indexes': [models.Index(fields=['record_code', 'name'], name='record_record__9bbf68_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserHasOccupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbo.occupation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_has_occupation',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='occupations',
            field=models.ManyToManyField(related_name='users', through='cbo.UserHasOccupation', to='cbo.occupation', verbose_name='Ocupação'),
        ),
        migrations.CreateModel(
            name='FavoriteProceduresFolderHasProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_procedures_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cbo.favoriteproceduresfolder')),
                ('procedure', models.ForeignKey(db_column='procedure_code', on_delete=django.db.models.deletion.CASCADE, to='cbo.procedure')),
            ],
            options={
                'db_table': 'favorite_procedures_folder_has_procedure',
                'unique_together': {('procedure', 'favorite_procedures_folder')},
            },
        ),
        migrations.CreateModel(
            name='ProcedureHasCid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_principal', models.CharField(max_length=4)),
                ('competence_date', models.CharField(max_length=6)),
                ('cid', models.ForeignKey(db_column='cid_code', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cids_has_procedure', to='cbo.cid')),
                ('procedure', models.ForeignKey(db_column='procedure_code', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procedures_has_cid', to='cbo.procedure')),
            ],
            options={
                'db_table': 'procedure_has_cid',
                'indexes': [models.Index(fields=['procedure', 'cid'], name='procedure_h_procedu_3bd432_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProcedureHasOccupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competence_date', models.CharField(max_length=6)),
                ('occupation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='occupations_has_procedure', to='cbo.occupation')),
                ('procedure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procedures_has_occupation', to='cbo.procedure')),
            ],
            options={
                'db_table': 'procedure_has_occupation',
                'indexes': [models.Index(fields=['procedure', 'occupation'], name='procedure_h_procedu_efe501_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProcedureHasRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competence_date', models.CharField(max_length=6)),
                ('procedure', models.ForeignKey(db_column='procedure_code', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procedures_has_record', to='cbo.procedure')),
                ('record', models.ForeignKey(db_column='record_code', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records_has_procedure', to='cbo.record')),
            ],
            options={
                'db_table': 'procedure_has_record',
                'indexes': [models.Index(fields=['procedure', 'record'], name='procedure_h_procedu_74a3ae_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['first_name', 'occupational_registration'], name='user_first_n_048813_idx'),
        ),
    ]
