# Generated by Django 4.2.6 on 2024-04-16 17:40

import cbo.models.managers.user
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('CPF', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='endereço de email')),
                ('telephone', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField(default='2000-01-01')),
                ('occupational_registration', models.CharField(max_length=15)),
                ('email_verified', models.BooleanField(default=False)),
                ('email_verification_token', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
            managers=[
                ('objects', cbo.models.managers.user.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Cid',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('cid_code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('grievance_type', models.CharField(max_length=1)),
                ('sex_type', models.CharField(max_length=1)),
                ('stadium_stype', models.CharField(max_length=1)),
                ('irradiated_fields_value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cbo_favorite_folder',
            },
        ),
        migrations.CreateModel(
            name='FavoriteProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cbo_favorite_procedure',
            },
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('occupation_code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('max_occupations', models.PositiveIntegerField()),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlanPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('point_description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'cbo_plan_point',
            },
        ),
        migrations.CreateModel(
            name='PlanPointAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('available', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'cbo_plan_point_availability',
            },
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('procedure_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, null=True)),
                ('complexity_type', models.CharField(max_length=1, null=True)),
                ('sex_type', models.CharField(max_length=1, null=True)),
                ('maximum_execution_amount', models.IntegerField(null=True)),
                ('stay_day_number', models.CharField(max_length=4, null=True)),
                ('points_number', models.IntegerField(null=True)),
                ('minimum_age_value', models.IntegerField(null=True)),
                ('maximum_age_value', models.IntegerField(null=True)),
                ('SH_value', models.IntegerField(null=True)),
                ('SA_value', models.IntegerField(null=True)),
                ('SP_value', models.IntegerField(null=True)),
                ('stay_time_number', models.IntegerField(null=True)),
                ('competence_date', models.CharField(max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('record_code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('competence_date', models.CharField(max_length=6)),
            ],
            options={
                'indexes': [models.Index(fields=['record_code', 'name'], name='cbo_record_record__6b63c2_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProcedureHasRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('competence_date', models.CharField(max_length=6)),
                ('procedure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procedures_has_record', to='cbo.procedure')),
                ('record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records_has_procedure', to='cbo.record')),
            ],
            options={
                'db_table': 'cbo_procedure_has_record',
            },
        ),
        migrations.CreateModel(
            name='ProcedureHasOccupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('competence_date', models.CharField(max_length=6)),
                ('occupation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='occupations_has_procedure', to='cbo.occupation')),
                ('procedure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procedures_has_occupation', to='cbo.procedure')),
            ],
            options={
                'db_table': 'cbo_procedure_has_occupation',
            },
        ),
        migrations.CreateModel(
            name='ProcedureHasCid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('st_principal', models.CharField(max_length=4)),
                ('competence_date', models.CharField(max_length=6)),
                ('cid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cids_has_procedure', to='cbo.cid')),
                ('procedure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procedures_has_cid', to='cbo.procedure')),
            ],
            options={
                'db_table': 'cbo_procedure_has_cid',
            },
        ),
        migrations.AddIndex(
            model_name='procedure',
            index=models.Index(fields=['procedure_code', 'name'], name='cbo_procedu_procedu_32c72d_idx'),
        ),
        migrations.AddField(
            model_name='planpointavailability',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbo.plan'),
        ),
        migrations.AddField(
            model_name='planpointavailability',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_point', to='cbo.planpoint'),
        ),
        migrations.AddField(
            model_name='plan',
            name='points',
            field=models.ManyToManyField(related_name='plans', through='cbo.PlanPointAvailability', to='cbo.planpoint'),
        ),
        migrations.AddIndex(
            model_name='occupation',
            index=models.Index(fields=['occupation_code', 'name'], name='cbo_occupat_occupat_17e032_idx'),
        ),
        migrations.AddField(
            model_name='favoriteprocedure',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cbo.favoritefolder'),
        ),
        migrations.AddField(
            model_name='favoriteprocedure',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbo.procedure'),
        ),
        migrations.AddField(
            model_name='favoriteprocedure',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favoritefolder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='cid',
            index=models.Index(fields=['cid_code', 'name'], name='cbo_cid_cid_cod_c08b9e_idx'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='occupations',
            field=models.ManyToManyField(related_name='users', to='cbo.occupation'),
        ),
        migrations.AddField(
            model_name='user',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='cbo.plan'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='procedurehasrecord',
            index=models.Index(fields=['procedure', 'record'], name='cbo_procedu_procedu_7fced0_idx'),
        ),
        migrations.AddIndex(
            model_name='procedurehasoccupation',
            index=models.Index(fields=['procedure', 'occupation'], name='cbo_procedu_procedu_1ac35f_idx'),
        ),
        migrations.AddIndex(
            model_name='procedurehascid',
            index=models.Index(fields=['procedure', 'cid'], name='cbo_procedu_procedu_03e71f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favoriteprocedure',
            unique_together={('user', 'procedure', 'folder')},
        ),
        migrations.AlterUniqueTogether(
            name='favoritefolder',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['first_name', 'occupational_registration'], name='cbo_user_first_n_b90126_idx'),
        ),
    ]
