# Generated by Django 4.2.6 on 2025-06-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='occupational_registration',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
