# Generated by Django 4.2.6 on 2024-09-21 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbo', '0003_patient_medicalrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='record_type',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
