# Generated by Django 5.2.2 on 2026-01-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Código da competência no formato YYYYMM ou com 9999 para vigências atemporais', max_length=6, unique=True)),
                ('is_atemporal', models.BooleanField(db_index=True, default=False, help_text='Indica se a competência é atemporal (vigência permanente)')),
                ('year', models.IntegerField(blank=True, help_text='Ano da competência (extraído do código quando aplicável)', null=True)),
                ('month', models.IntegerField(blank=True, help_text='Mês da competência (1-12, quando aplicável)', null=True)),
                ('formatted_date', models.CharField(blank=True, help_text='Data formatada MM/YYYY para exibição', max_length=10, null=True)),
                ('description', models.TextField(blank=True, help_text='Descrição adicional da competência')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Competência',
                'verbose_name_plural': 'Competências',
                'db_table': 'competence',
                'ordering': ['-code'],
                'indexes': [models.Index(fields=['code'], name='competence_code_1f79be_idx'), models.Index(fields=['is_atemporal'], name='competence_is_atem_10dad8_idx'), models.Index(fields=['-year', '-month'], name='competence_year_394b02_idx')],
            },
        ),
    ]
