# Generated by Django 5.2.2 on 2026-01-12 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbo', '0002_competence'),
    ]

    operations = [
        migrations.CreateModel(
            name='SigtapSyncHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de início da sincronização')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Data e hora de conclusão da sincronização', null=True)),
                ('status', models.CharField(choices=[('in_progress', 'Em Progresso'), ('success', 'Sucesso'), ('failed', 'Falha'), ('partial', 'Parcial')], db_index=True, default='in_progress', help_text='Status da sincronização', max_length=20)),
                ('competence_code', models.CharField(blank=True, help_text='Código da competência sincronizada (YYYYMM)', max_length=6, null=True)),
                ('files_processed', models.IntegerField(default=0, help_text='Número de arquivos processados')),
                ('files_total', models.IntegerField(default=0, help_text='Número total de arquivos esperados')),
                ('procedures_count', models.IntegerField(default=0, help_text='Total de procedimentos após sincronização')),
                ('occupations_count', models.IntegerField(default=0, help_text='Total de ocupações após sincronização')),
                ('cids_count', models.IntegerField(default=0, help_text='Total de CIDs após sincronização')),
                ('records_count', models.IntegerField(default=0, help_text='Total de registros após sincronização')),
                ('competences_synced', models.IntegerField(default=0, help_text='Total de competências sincronizadas')),
                ('error_message', models.TextField(blank=True, help_text='Mensagem de erro, se houver')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Detalhes adicionais da sincronização (arquivos, logs, etc.)')),
                ('duration_seconds', models.FloatField(blank=True, help_text='Duração da sincronização em segundos', null=True)),
                ('is_automatic', models.BooleanField(default=False, help_text='Indica se foi uma sincronização automática')),
                ('triggered_by', models.ForeignKey(blank=True, help_text='Usuário que iniciou a sincronização (se manual)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sigtap_syncs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Sincronização SIGTAP',
                'verbose_name_plural': 'Históricos de Sincronização SIGTAP',
                'db_table': 'sigtap_sync_history',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['-started_at'], name='sigtap_sync_started_48a5c5_idx'), models.Index(fields=['status'], name='sigtap_sync_status_48f0d7_idx'), models.Index(fields=['competence_code'], name='sigtap_sync_compete_93f704_idx')],
            },
        ),
    ]
